### ISSUE TITLE
Old age of evidences.

### ISSUE THREAD

**Issue by nappies** [razvanmarinescu/EB1A#1]
Razvan, thanks for the great tutorial!
I have one question I am a musician.I have been doing this for a long time.And used to actively participate in competitions had wins.And then I focused on music and listeners. Can I use enough old wins and publications?Approximately 2009. Does it matter?

**Comment by razvanmarinescu** [comment]
Hi! Glad you found it useful! Yes, you can use older evidence from 2009, as long as it's within your field of endeavour on which you make the application (or as long as it fits your application's narrative well). However, it would also be important to show that you *sustained* that performance since 2009 (e.g. through other awards, activities, concerts, etc ..).

**Comment by nappies** [comment]
Thank you for fast answer!
